config/routes.rb
Ticket::Application.routes.draw do
  resources :events do
    member do
      post :buy
    end
  end
  
  resources :coupons

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  match 'l/:id_base62' => 'share_urls#hit'
  match 'share_urls/share' => 'share_urls#share'
  match '/share_urls/not_share' => 'share_urls#not_share'
  match '/referral/visit' => 'admin/referral#visit', :via => :post
  match '/image_proxy' => 'share_urls#image_proxy'
  
  namespace :admin do
    namespace :referral do
      get 'dashboard'
    end
  end
    
  match 'cadastro' => 'application#cadastro'
  match 'buy' => 'application#buy'

  root :to => "application#home"

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :event, :counter_cache => true
  belongs_to :user
  
  scope :available, :conditions => "user_id IS NULL"
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /coupons
  # GET /coupons.xml
  def index
    @coupons = Coupon.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @coupons }
    end
  end

  # GET /coupons/1
  # GET /coupons/1.xml
  def show
    @coupon = Coupon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

  # GET /coupons/new
  # GET /coupons/new.xml
  def new
    @coupon = Coupon.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

  # GET /coupons/1/edit
  def edit
    @coupon = Coupon.find(params[:id])
  end

  # POST /coupons
  # POST /coupons.xml
  def create
    @coupon = Coupon.new(params[:coupon])

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to(@coupon, :notice => 'Coupon was successfully created.') }
        format.xml  { render :xml => @coupon, :status => :created, :location => @coupon }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /coupons/1
  # PUT /coupons/1.xml
  def update
    @coupon = Coupon.find(params[:id])

    respond_to do |format|
      if @coupon.update_attributes(params[:coupon])
        format.html { redirect_to(@coupon, :notice => 'Coupon was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.xml
  def destroy
    @coupon = Coupon.find(params[:id])
    @coupon.destroy

    respond_to do |format|
      format.html { redirect_to(coupons_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<%= form_for(@coupon) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<h1>Listing coupons</h1>

<table>
  <tr>
    <th>Price</th>
    <th>Title</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coupons.each do |coupon| %>
  <tr>
    <td><%= coupon.price %></td>
    <td><%= coupon.title %></td>
    <td><%= coupon.event_id %></td>
    <td><%= link_to 'Show', coupon %></td>
    <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
    <td><%= link_to 'Destroy', coupon, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
  <div id="share_<%= coupon.id %>" class="share"></div><!-- #share -->

  <script type="text/javascript">
    $.referral.facebook.append({
      appendTo: '#share_<%= coupon.id %>',
      html: 'facebook',
      name: '<%= coupon.title %>',
      link: '<%= share_url(current_user.id, coupon.id, "Coupon") %>',
      picture: 'http://fumsoft.no-ip.org:3000/image_proxy?url=<%= CGI.escape share_url(current_user.id, coupon.id, "Coupon") %>&image=<%= CGI.escape "/images/rails.png" %>',
      caption: 'Aplicativo de teste',
      description: 'Descricao do app'
    });
    
    $.referral.twitter.append({
      appendTo: '#share_<%= coupon.id %>',
      html: 'twitter',
      url: '<%= share_url(current_user.id, coupon.id, "Coupon") %>',
      via: 'Nome do app',
      text: 'Texto do Tweet'
    });
  </script>
<% end %>
</table>

<br />

<%= link_to 'New Coupon', new_coupon_path %>

app/views/coupons/new.html.erb
<h1>New coupon</h1>

<%= render 'form' %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Price:</b>
  <%= @coupon.price %>
</p>

<p>
  <b>Title:</b>
  <%= @coupon.title %>
</p>

<p>
  <b>Event:</b>
  <%= @coupon.event_id %>
</p>


<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>