config/routes.rb
Ticket::Application.routes.draw do
  resources :events do
    member do
      post :buy
    end
  end
  
  resources :coupons

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  match 'l/:id_base62' => 'share_urls#hit'
  match 'share_urls/share' => 'share_urls#share'
  match '/share_urls/not_share' => 'share_urls#not_share'
  match '/referral/visit' => 'admin/referral#visit', :via => :post
  match '/image_proxy' => 'share_urls#image_proxy'
  
  namespace :admin do
    namespace :referral do
      get 'dashboard'
    end
  end
    
  match 'cadastro' => 'application#cadastro'
  match 'buy' => 'application#buy'

  root :to => "application#home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ticket</title>
  <%= stylesheet_link_tag 'reset', 'style' %>
  <%= javascript_include_tag 'jquery-1.6.2', 'rails', 'jquery.referral', 'application' %>
  <%= csrf_meta_tag %>
  
  <script type="text/javascript">
    $.referral.init({
      facebook: {
        appId: '186093064798328', //206193506102746
      } //facebook
    });
  </script>
</head>
<body>
<div id="app">
  <div id="header">
    <div class="wrapper">
      <div id="logo">
        <%= link_to image_tag('logo.png'), root_url %>
      </div><!-- #logo -->
      <% if user_signed_in? %>
        <div id="dashboard">
          <p>Olá, <strong><%= current_user.name %></strong>! Você tem <strong><%= pluralize(current_user.coupons.count, 'ingresso', 'ingressos') %></strong> e <strong>R$<%= current_user.credit %> de crédito</strong> - <%= link_to 'sair', destroy_user_session_path, :method => :delete %></p>
        </div><!-- #dashboard -->
      <% else %>
        <div id="login">        
          <%= form_for(User.new, :as => :user, :url => session_path(:user)) do |f| %>
            <label>Fazer login:</label>
            <%= f.email_field :email, :placeholder => "E-mail" %>
            <%= f.password_field :password, :placeholder => "Senha" %>
            
            <%= f.submit "Entrar" %>
            
            ou 
            
            <%= link_to "Cadastre-se", new_registration_path(:user) %>
          <% end %>
        </div><!-- #login -->
      <% end %>
    </div><!-- .wrapper -->
  </div><!-- #header -->
  <div id="main">
    <% if params[:m] %>
      <p class="flash-message">
        <% if params[:m] == '1' %>
          Compra feita com sucesso
        <% end %>
      </p>
    <% end %>
    <%= yield %>
  </div><!-- #main -->
</div><!-- #app -->

</body>
</html>

app/views/layouts/referral.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Referral Admin</title>
  <%= stylesheet_link_tag 'reset', 'admin/referral/application' %>
  <%= javascript_include_tag 'jquery-1.6.2', 'jquery.referral', 'admin/referral/highcharts', 'admin/referral/funnel' %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="app">
  
    <div class="wrapper">
  <div id="header">
      <h1><span class="text">Referral admin</span></h1>
  </div><!-- #header -->
  
    </div><!-- .wrapper -->
  <%= yield %>
</div><!-- #app -->

</body>
</html>